Update test_update_coverage_on_readme.yml

diff --git a/.github/workflows/test_update_coverage_on_readme.yml b/.github/workflows/test_update_coverage_on_readme.yml
--- a/.github/workflows/test_update_coverage_on_readme.yml
+++ b/.github/workflows/test_update_coverage_on_readme.yml
@@ -43,12 +43,11 @@ jobs:
       run: |
         pip install pytest pytest-cov
         pip install -e .
-        set -o pipefail
-        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=ImgDataConvertCodeGen tests/ | tee pytest-coverage.txt
+        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=ImgDataConvertCodeGen tests/ > pytest-coverage.txt || echo "::set-output name=pytest_failed::true"
 
-        
+
     - name: Pytest coverage comment
-      if: steps.test.outcome == 'success'  
+      if: steps.test.outputs.pytest_failed != 'true' 
       id: coverageComment
       uses: MishaKav/pytest-coverage-comment@main
       with:
@@ -56,14 +55,16 @@ jobs:
         junitxml-path: ./pytest.xml
         hide-report: true
 
-    - name: Update README based on tests outcome
+    - name: Update README with Coverage Badge
+      if: steps.test.outputs.pytest_failed != 'true'
       run: |
-        if [ ${{ job.status }} == 'success' ]; then
-          sed -i '/.. Pytest Coverage\/Status Comment:Begin/,/.. Pytest Coverage\/Status Comment:End/c\.. Pytest Coverage\/Status Comment:Begin\n\n.. image:: https://img.shields.io/badge/Coverage-${{ steps.coverageComment.outputs.coverage }}-${{ steps.coverageComment.outputs.color }}.svg\n   :target: https://github.com/c3di/ImgDataConvertCodeGen/blob/master/README.rst#code-coverage\n   :alt: Coverage\n\n.. Pytest Coverage\/Status Comment:End' ./README.rst
-        else
-          sed -i '/.. Pytest Coverage\/Status Comment:Begin/,/.. Pytest Coverage\/Status Comment:End/c\.. Pytest Coverage\/Status Comment:Begin\n\n.. image:: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests.yml/badge.svg\n    :target: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests.yml\n    :alt: tests\n\n.. Pytest Coverage\/Status Comment:End' ./README.rst
-        fi
-      shell: bash
+        sed -i '/.. Pytest Coverage\/Status Comment:Begin/,/.. Pytest Coverage\/Status Comment:End/c\.. Pytest Coverage\/Status Comment:Begin\n\n.. image:: https://img.shields.io/badge/Coverage-${{ steps.coverageComment.outputs.coverage }}-${{ steps.coverageComment.outputs.color }}.svg\n   :target: https://github.com/c3di/ImgDataConvertCodeGen/blob/master/README.rst#code-coverage\n   :alt: Coverage\n\n.. Pytest Coverage\/Status Comment:End' ./README.rst
+      
+    - name: Update README with Failed Status Badge
+      if: steps.test.outputs.pytest_failed == 'true'
+      run: |
+        sed -i '/.. Pytest Coverage\/Status Comment:Begin/,/.. Pytest Coverage\/Status Comment:End/c\.. Pytest Coverage\/Status Comment:Begin\n\n.. image:: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests.yml/badge.svg?event=push\n    :target: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests.yml\n    :alt: Tests Failed\n\n.. Pytest Coverage\/Status Comment:End' ./README.rst
+
       
     - name: Commit & Push changes to Readme
       uses: actions-js/push@master
